services:
  http:
    build: .
    command: [
      "-config", "/etc/app/prod.yaml",
    ]
    environment:
      IR_HTTP_PORT: 8000
      IR_POSTGRES_URI: ${IR_POSTGRES_URI}
      IR_JWT_SECRET: ${IR_JWT_SECRET}
      IR_HTTP_CORS_ALLOW_ORIGINS: ${IR_HTTP_CORS_ALLOW_ORIGINS:-}
      IR_PROXY_URL: ${IR_PROXY_URL:-}
      PGSSLROOTCERT: /certs/root.crt
    ports:
      - "${EXTERNAL_HTTP_PORT:-8000}:8000"
    volumes:
      - ./config:/etc/app:ro
      - ${PGSSLROOTCERT}:/certs:ro
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-batch-size: "100"
        loki-retries: 2
        loki-max-backoff: 1000ms
        loki-timeout: 1s
    networks:
      - internal

  migrate:
    image: migrate/migrate
    command: [
      "-path", "/migrations",
      "-database", "${IR_POSTGRES_URI}",
      "up"
    ]
    environment:
      PGSSLROOTCERT: /certs/root.crt
    volumes:
      - ./migrations:/migrations:ro
      - ${PGSSLROOTCERT}:/certs:ro

  loki:
    hostname: loki
    image: grafana/loki:latest
    ports:
      - "${EXTERNAL_LOKI_PORT:-3100}:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - internal

networks:
  internal:
    driver: bridge
