DROP TABLE IF EXISTS usernames;
DROP TABLE IF EXISTS answers;
DROP TABLE IF EXISTS threads;
DROP TABLE IF EXISTS participants;
DROP TABLE IF EXISTS edges;
DROP TABLE IF EXISTS options;
DROP TABLE IF EXISTS bot_messages;
DROP TABLE IF EXISTS entries;
DROP TABLE IF EXISTS nodes;
DROP TABLE IF EXISTS bots;

DROP TYPE  IF EXISTS OPERATION;
DROP TYPE  IF EXISTS PREDICATE_T;
