openapi: 3.0.3
info:
  title: ITS Reg API
  description: ITS Reg API
  version: 2.0.0
servers:
  - url: 'http://{localhost}:{port}/api/v2'
    variables:
      hostname:
        default: localhost
      port:
        default: "8400"
security:
  - bearerAuth: []

paths:
  /bots:
    put:
      operationId: createBot
      description: Создать или заменить существующего бота с данным ID.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutBots'
      responses:
        "201":
          description: Бот успешно создан.
        "400":
          description: Данные в запросе невалидны.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Не был указан JWT токен.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "403":
          description: Бот с данным ID уже существует, нет доступа к его обновлению
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    get:
      operationId: getBots
      description: Получить информацию о ботах пользователя
      responses:
        "200":
          description: Успешно получена информация о ботах.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bot'
        "400":
          description: "Данные в запросе невалидны."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Не был указан JWT токен.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /bots/{id}:
    get:
      operationId: getBot
      description: Получить информацию о боте с указанным ID.
      parameters:
        - in: path
          name: id
          schema:
            type: string
            example: example_bot
          required: true
          description: Уникальный ID бота.
      responses:
        "200":
          description: Бот найден.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bot'
        "400":
          description: Данные в запросе невалидны.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Не был указан JWT токен.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "403":
          description: Нет доступа к боту с данным UUID.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: Бот с данным UUID не найден.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /bots/{id}/answers:
    get:
      operationId: getAnswers
      description: Получить ответы участников на бота с данным ID в формате CSV.
      parameters:
        - in: path
          name: id
          schema:
            type: string
            example: example_bot
          required: true
          description: Уникальный ID бота.
      responses:
        "200":
          description: Успешно получены ответы участников.
          content:
            text/csv: { }
        "400":
          description: Данные в запросе невалидны.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Не был указан JWT токен.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "403":
          description: Нет доступа к боту с данным ID.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: Бот с данным ID не найден.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /bots/{id}/start:
    post:
      operationId: startBot
      description: Запустить бота с указанным ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
            example: example_bot
          required: true
          description: Уникальный ID бота.
      responses:
        "200":
          description: Бот успешно запущен.
        "400":
          description: Данные в запросе невалидны.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Не был указан JWT токен.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "403":
          description: Нет доступа к боту с данным ID.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: Бот с данным ID не найден.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /bots/{id}/stop:
    post:
      operationId: stopBot
      description: Отправить запрос на остановку бота с данным ID.
      parameters:
        - in: path
          name: id
          schema:
            type: string
            example: example_bot
          required: true
          description: Уникальный ID бота.
      responses:
        "200":
          description: Бот успешно остановлен.
        "400":
          description: Данные в запросе невалидны.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Не был указан JWT токен.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "403":
          description: Нет доступа к боту с данным ID.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: Бот с данным ID не найден.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Predicate:
      type: object
      description: Predicate описывает условие перехода по ребру.
      oneOf:
        - $ref: '#/components/schemas/AlwaysPredicate'
        - $ref: '#/components/schemas/ExactPredicate'
        - $ref: '#/components/schemas/RegexpPredicate'
      discriminator:
        propertyName: type
        mapping:
          always: '#/components/schemas/AlwaysPredicate'
          exact:  '#/components/schemas/ExactPredicate'
          regexp: '#/components/schemas/RegexpPredicate'

    AlwaysPredicate:
      type: object
      description: Переход по ребру осуществляется на любое сообщение пользователя.
      properties:
        type:
          type: string
          enum: [always]
      required:
        - type

    ExactPredicate:
      type: object
      description: Переход по ребру осуществляется при полном совпадении строки text с сообщением пользователя.
      properties:
        type:
          type: string
          enum: [exact]
        text:
          type: string
      required:
        - type
        - text

    RegexpPredicate:
      type: object
      description: Переход по ребру осуществляется при совпадении с регулярным выражением pattern.
      properties:
        type:
          type: string
          enum: [regexp]
        pattern:
          type: string
      required:
        - type
        - pattern

    Edge:
      type: object
      description: Обозначают связь между узлами как переход в результате ответа пользователя.
      properties:
        predicate:
          $ref: '#/components/schemas/Predicate'
        to:
          type: integer
          description: State узла, к которому совершается переход.
        operation:
          type: string
          description: >
            Действие, которое выполнится в результате перехода пользователя по ребру.
            - noop. Ничего не происходит. Подходит для использования в меню и промежуточных узлах.
            - save. Сохраняет ответ или перезаписывает предыдущий. Подходит в большинстве ситуаций.
            - append. Добавляет ответ к предыдущему. Подходит для вопросов с множественным выбором.
          enum:
            - noop
            - save
            - append
      required:
        - predicate
        - to
        - operation

    Message:
      type: object
      description: Любое сообщение в Telegram. На данный момент описывается текстом, но в будущем добавится поддержка файлов.
      properties:
        text:
          type: string
      required:
        - text

    BotMessage:
      type: object
      description: Сообщение от бота. Отличается от базового сообщения наличием опций (кнопок).
      properties:
        message:
          $ref: '#/components/schemas/Message'
        options:
          type: array
          items:
            type: string
      required:
        - message
        - options

    Node:
      type: object
      description: >
        Минимальная структурная единица сценария бота. Представляет собой сообщение (сообщения), которые отправляются
        пользователю. Ожидается ответ пользователя для перехода к следующему узлу.
      properties:
        state:
          type: integer
          description: Уникальный номер узла в сценарии бота.
        title:
          type: string
          description: Человеко-читаемое название узла. В таблице ответов будет отображаться как заголовок столбца.
        edges:
          type: array
          items:
            $ref: '#/components/schemas/Edge'
        messages:
          type: array
          items:
            $ref: '#/components/schemas/BotMessage'
      required:
        - state
        - title
        - messages

    Entry:
      type: object
      description: >
        Точка входа в сценарий бота. Пользователь может вызвать точку входу командой /<entry> (как, например, /start).
        Может быть вызвана рассылкой по такому же ключу.
      properties:
        key:
          type: string
          description: Ключ точки входа.
        start:
          type: integer
          description: Указатель на State узла, с которого начинается выполнение сценария.
      required:
        - key
        - start

    Script:
      type: object
      description: Сценарий бота.
      properties:
        nodes:
          type: array
          items:
            $ref: '#/components/schemas/Node'
        entries:
          type: array
          items:
            $ref: '#/components/schemas/Entry'
      required:
        - nodes
        - entries

    Bot:
      type: object
      properties:
        id:
          type: string
          description: Уникальный ID бота.
        token:
          type: string
          description: Телеграм токен для бота, полученный в @BotFather.
        author:
          type: integer
          format: int64
          description: ID пользователя - автора бота.
        script:
          $ref: '#/components/schemas/Script'
      required:
        - id
        - token
        - author
        - script

    PutBots:
      type: object
      properties:
        id:
          type: string
          description: Уникальный ID бота.
        token:
          type: string
          description: Телеграм токен для бота, полученный в @BotFather.
        script:
          $ref: '#/components/schemas/Script'
      required:
        - id
        - token
        - script

    Error:
      type: object
      properties:
        message:
          type: string
        slug:
          type: string
      required:
        - message
