// Package apiv3 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.0 DO NOT EDIT.
package apiv3

import (
	"encoding/json"
	"errors"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for AlwaysPredicateType.
const (
	Always AlwaysPredicateType = "always"
)

// Defines values for EdgeOperation.
const (
	Append EdgeOperation = "append"
	Noop   EdgeOperation = "noop"
	Save   EdgeOperation = "save"
)

// Defines values for ExactPredicateType.
const (
	Exact ExactPredicateType = "exact"
)

// Defines values for MailingStatus.
const (
	MailingStatusCompleted MailingStatus = "completed"
	MailingStatusFailed    MailingStatus = "failed"
	MailingStatusScheduled MailingStatus = "scheduled"
	MailingStatusStarted   MailingStatus = "started"
)

// Defines values for RegexPredicateType.
const (
	Regex RegexPredicateType = "regex"
)

// Defines values for RunStatus.
const (
	RunStatusActive   RunStatus = "active"
	RunStatusFailed   RunStatus = "failed"
	RunStatusStarting RunStatus = "starting"
	RunStatusStopped  RunStatus = "stopped"
)

// AlwaysPredicate Переход по ребру осуществляется на любое сообщение пользователя.
type AlwaysPredicate struct {
	Type AlwaysPredicateType `json:"type"`
}

// AlwaysPredicateType defines model for AlwaysPredicate.Type.
type AlwaysPredicateType string

// Bot Сущность, связывающая между собой сценарий (Script) и запуски телеграм-бота (Run).
type Bot struct {
	// CreatedAt Метка времени создания бота.
	CreatedAt time.Time `json:"createdAt"`

	// Desc Человекочитаемое описание назначения бота.
	Desc string `json:"desc"`

	// Id Уникальный ID бота.
	Id string `json:"id"`

	// OwnerID ID владельца бота.
	OwnerID int64 `json:"ownerID"`

	// ScriptID ID сценария для бота.
	ScriptID string `json:"scriptID"`

	// UpdatedAt Метка времени последнего обновления бота.
	UpdatedAt time.Time `json:"updatedAt"`
}

// CreateBotRequest defines model for CreateBotRequest.
type CreateBotRequest struct {
	// Desc Человекочитаемое описание назначения бота.
	Desc string `json:"desc"`

	// ScriptID ID сценария для бота.
	ScriptID string `json:"scriptID"`

	// Token Telegram-токен бота, полученный через @BotFather. Должен быть уникальным для всех ботов.
	Token Token `json:"token"`
}

// CreateBotResponse defines model for CreateBotResponse.
type CreateBotResponse struct {
	// BotID Уникальный ID бота.
	BotID string `json:"botID"`
}

// CreateMailingRequest defines model for CreateMailingRequest.
type CreateMailingRequest struct {
	// BotID ID бота, для которого будет запланирована рассылка.
	BotID string `json:"botID"`

	// EntryKey Ключ точки входа сценария бота, которая будет вызвана в рассылке.
	EntryKey string `json:"entryKey"`

	// Name Человекочитаемое название рассылки.
	Name string `json:"name"`

	// Recipients Массив ID пользователей, которым будет отправлена рассылка.
	Recipients []int64 `json:"recipients"`
}

// CreateMailingResponse defines model for CreateMailingResponse.
type CreateMailingResponse struct {
	// MailingID Уникальный ID рассылки.
	MailingID string `json:"mailingID"`
}

// CreateRunResponse defines model for CreateRunResponse.
type CreateRunResponse struct {
	// RunID Уникальный ID запуска бота.
	RunID string `json:"runID"`
}

// CreateScriptRequest defines model for CreateScriptRequest.
type CreateScriptRequest struct {
	// Desc Человекочитаемое описание назначения сценария.
	Desc string `json:"desc"`

	// Entries Неупорядоченный непустой массив точек входа сценария.
	Entries []Entry `json:"entries"`

	// Nodes Неупорядоченный непустой массив узлов сценария.
	Nodes []Node `json:"nodes"`
}

// CreateScriptResponse defines model for CreateScriptResponse.
type CreateScriptResponse struct {
	// ScriptID Уникальный ID сценария.
	ScriptID string `json:"scriptID"`
}

// Edge Обозначают связь между узлами как переход в результате ответа пользователя.
type Edge struct {
	// Operation Действие, которое выполнится в результате перехода пользователя по ребру. - noop. Ничего не происходит. Подходит для использования в меню и промежуточных узлах. - save. Сохраняет ответ или перезаписывает предыдущий. Подходит в большинстве ситуаций. - append. Добавляет ответ к предыдущему. Подходит для вопросов с множественным выбором.
	Operation EdgeOperation `json:"operation"`

	// Predicate Predicate описывает условие перехода по ребру.
	Predicate Predicate `json:"predicate"`

	// To State узла, к которому совершается переход.
	To int `json:"to"`
}

// EdgeOperation Действие, которое выполнится в результате перехода пользователя по ребру. - noop. Ничего не происходит. Подходит для использования в меню и промежуточных узлах. - save. Сохраняет ответ или перезаписывает предыдущий. Подходит в большинстве ситуаций. - append. Добавляет ответ к предыдущему. Подходит для вопросов с множественным выбором.
type EdgeOperation string

// Entry Точка входа в сценарий бота. Пользователь может вызвать точку входу командой /<entry> (как, например, /start). Может быть вызвана рассылкой по такому же ключу.
type Entry struct {
	// Key Ключ точки входа.
	Key string `json:"key"`

	// Start Указатель на State узла, с которого начинается выполнение сценария.
	Start int `json:"start"`
}

// ExactPredicate Переход по ребру осуществляется при полном совпадении строки text с сообщением пользователя.
type ExactPredicate struct {
	Text string             `json:"text"`
	Type ExactPredicateType `json:"type"`
}

// ExactPredicateType defines model for ExactPredicate.Type.
type ExactPredicateType string

// GetBotResponse Сущность, связывающая между собой сценарий (Script) и запуски телеграм-бота (Run).
type GetBotResponse = Bot

// GetBotsResponse defines model for GetBotsResponse.
type GetBotsResponse = []Bot

// GetScriptResponse Сценарий бота. Является объединением узлов (Node), точек входа (Entry). Гарантируется связность всех узлов относительно любой точки входа Entry.
type GetScriptResponse = Script

// GetScriptsResponse defines model for GetScriptsResponse.
type GetScriptsResponse = []Script

// Mailing Сущность, обозначающая запланированную или уже выполненную рассылку.
type Mailing struct {
	// BotID ID бота, для которого была запланирована рассылка.
	BotID string `json:"botID"`

	// CompletedAt Метка времени завершения рассылки.
	CompletedAt *time.Time `json:"completedAt,omitempty"`

	// CreatedAt Метка времени создания рассылки.
	CreatedAt time.Time `json:"createdAt"`

	// EntryKey Ключ точки входа сценария бота, которая будет вызвана в рассылке.
	EntryKey string `json:"entryKey"`

	// FailCount Количество неудачных отправок рассылки пользователям.
	FailCount int `json:"failCount"`

	// Id Уникальный ID рассылки.
	Id string `json:"id"`

	// Name Человекочитаемое название рассылки.
	Name string `json:"name"`

	// PendingCount Количество отправок рассылки пользователям, которые ещё не были завершены.
	PendingCount int `json:"pendingCount"`

	// Recipients Массив ID пользователей, которым будет отправлена рассылка.
	Recipients []int64 `json:"recipients"`

	// Results Массив результатов рассылки для каждого пользователя. Заполняется по мере выполнения рассылки.
	Results []UserMailingResult `json:"results"`

	// StartedAt Метка времени начала рассылки.
	StartedAt *time.Time `json:"startedAt,omitempty"`

	// Status Статус рассылки.
	Status MailingStatus `json:"status"`

	// SuccessCount Количество успешных отправок рассылки пользователям.
	SuccessCount int `json:"successCount"`

	// TotalCount Общее количество пользователей в рассылке.
	TotalCount int `json:"totalCount"`
}

// MailingStatus Статус рассылки.
type MailingStatus string

// Message Любое сообщение в Telegram. На данный момент описывается текстом, но в будущем добавится поддержка файлов.
type Message struct {
	Text string `json:"text"`
}

// Node Минимальная структурная единица сценария Script. Представляет собой: - сообщения, которые отправляются пользователю (Message); - исходящие рёбра, обозначающие переход пользователя к следующему состоянию (узлу, Node); - опции для пользователя (кнопки).
type Node struct {
	// Edges Массив исходящих рёбер узла.
	Edges *[]Edge `json:"edges,omitempty"`

	// Messages Массив отправляемых ботом сообщений при вхождении в узел.
	Messages []Message `json:"messages"`

	// Options Массив кнопок (опций) ответа для пользователя.
	Options *[]string `json:"options,omitempty"`

	// State Уникальный номер узла в сценарии бота.
	State int `json:"state"`

	// Title Человеко-читаемое название узла. В таблице ответов будет отображаться как заголовок столбца.
	Title string `json:"title"`
}

// PlainError defines model for PlainError.
type PlainError struct {
	// Message Сообщение об ошибке.
	Message string `json:"message"`
}

// Predicate Predicate описывает условие перехода по ребру.
type Predicate struct {
	union json.RawMessage
}

// RegexPredicate Переход по ребру осуществляется при совпадении с регулярным выражением pattern.
type RegexPredicate struct {
	Pattern string             `json:"pattern"`
	Type    RegexPredicateType `json:"type"`
}

// RegexPredicateType defines model for RegexPredicate.Type.
type RegexPredicateType string

// Run defines model for Run.
type Run struct {
	// BotID ID бота, который был запущен.
	BotID string `json:"botID"`

	// ErrorMsg Сообщение об ошибке, если статус запуска failed.
	ErrorMsg *string `json:"errorMsg,omitempty"`

	// Id Уникальный ID запуска бота.
	Id string `json:"id"`

	// StartedAt Метка времени запуска бота.
	StartedAt *time.Time `json:"startedAt,omitempty"`

	// Status Статус бота.
	Status RunStatus `json:"status"`

	// StoppedAt Метка времени остановки бота.
	StoppedAt *time.Time `json:"stoppedAt,omitempty"`
}

// RunStatus Статус бота.
type RunStatus string

// Script Сценарий бота. Является объединением узлов (Node), точек входа (Entry). Гарантируется связность всех узлов относительно любой точки входа Entry.
type Script struct {
	// CreatedAt Метка времени создания сценария.
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// Desc Человекочитаемое описание назначения сценария.
	Desc string `json:"desc"`

	// Entries Неупорядоченный непустой массив точек входа сценария.
	Entries []Entry `json:"entries"`

	// Id Уникальный ID сценария.
	Id *string `json:"id,omitempty"`

	// Nodes Неупорядоченный непустой массив узлов сценария.
	Nodes []Node `json:"nodes"`

	// UpdatedAt Метка времени последнего обновления сценария.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// Token Telegram-токен бота, полученный через @BotFather. Должен быть уникальным для всех ботов.
type Token = string

// UpdateBotRequest defines model for UpdateBotRequest.
type UpdateBotRequest struct {
	// Desc Человекочитаемое описание назначения бота.
	Desc *string `json:"desc,omitempty"`

	// ScriptID ID сценария для бота.
	ScriptID *string `json:"scriptID,omitempty"`

	// Token Telegram-токен бота, полученный через @BotFather. Должен быть уникальным для всех ботов.
	Token *Token `json:"token,omitempty"`
}

// UpdateBotResponse Сущность, связывающая между собой сценарий (Script) и запуски телеграм-бота (Run).
type UpdateBotResponse = Bot

// UpdateScriptResponse Сценарий бота. Является объединением узлов (Node), точек входа (Entry). Гарантируется связность всех узлов относительно любой точки входа Entry.
type UpdateScriptResponse = Script

// UserMailingResult Результат рассылки для одного пользователя.
type UserMailingResult struct {
	// ErrorMsg Сообщение об ошибке, если отправка рассылки пользователю не удалась.
	ErrorMsg *string `json:"errorMsg,omitempty"`

	// Success Успешность отправки рассылки пользователю.
	Success bool `json:"success"`

	// UserID ID пользователя, которому была отправлена рассылка.
	UserID int64 `json:"userID"`
}

// ValidationError defines model for ValidationError.
type ValidationError = []ValidationErrorDetail

// ValidationErrorDetail defines model for ValidationErrorDetail.
type ValidationErrorDetail struct {
	// Code Код ошибки валидации для данного поля.
	Code string `json:"code"`

	// Field Название поля, вызвавшего ошибку валидации.
	Field string `json:"field"`

	// Message Сообщение об ошибке валидации для данного поля.
	Message string `json:"message"`
}

// GetBotMailingsParams defines parameters for GetBotMailings.
type GetBotMailingsParams struct {
	// Status Статус рассылки для фильтрации. Если не указан, возвращаются рассылки всех статусов.
	Status *MailingStatus `form:"status,omitempty" json:"status,omitempty"`
}

// GetBotRunsParams defines parameters for GetBotRuns.
type GetBotRunsParams struct {
	// Status Статус запуска для фильтрации. Если не указан, возвращаются запуски всех статусов.
	Status *RunStatus `form:"status,omitempty" json:"status,omitempty"`
}

// GetMailingsParams defines parameters for GetMailings.
type GetMailingsParams struct {
	// BotID ID бота для фильтрации рассылок. Если не указан, возвращаются рассылки всех ботов пользователя.
	BotID *string `form:"botID,omitempty" json:"botID,omitempty"`

	// Status Статус рассылки для фильтрации. Если не указан, возвращаются рассылки всех статусов.
	Status *MailingStatus `form:"status,omitempty" json:"status,omitempty"`
}

// GetRunsParams defines parameters for GetRuns.
type GetRunsParams struct {
	// BotID ID бота для фильтрации запусков. Если не указан, возвращаются запуски всех ботов пользователя.
	BotID *string `form:"botID,omitempty" json:"botID,omitempty"`

	// Status Статус запуска для фильтрации. Если не указан, возвращаются запуски всех статусов.
	Status *RunStatus `form:"status,omitempty" json:"status,omitempty"`
}

// CreateBotJSONRequestBody defines body for CreateBot for application/json ContentType.
type CreateBotJSONRequestBody = CreateBotRequest

// UpdateBotJSONRequestBody defines body for UpdateBot for application/json ContentType.
type UpdateBotJSONRequestBody = UpdateBotRequest

// CreateMailingJSONRequestBody defines body for CreateMailing for application/json ContentType.
type CreateMailingJSONRequestBody = CreateMailingRequest

// CreateScriptJSONRequestBody defines body for CreateScript for application/json ContentType.
type CreateScriptJSONRequestBody = CreateScriptRequest

// UpdateScriptJSONRequestBody defines body for UpdateScript for application/json ContentType.
type UpdateScriptJSONRequestBody = Script

// AsAlwaysPredicate returns the union data inside the Predicate as a AlwaysPredicate
func (t Predicate) AsAlwaysPredicate() (AlwaysPredicate, error) {
	var body AlwaysPredicate
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAlwaysPredicate overwrites any union data inside the Predicate as the provided AlwaysPredicate
func (t *Predicate) FromAlwaysPredicate(v AlwaysPredicate) error {
	v.Type = "always"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAlwaysPredicate performs a merge with any union data inside the Predicate, using the provided AlwaysPredicate
func (t *Predicate) MergeAlwaysPredicate(v AlwaysPredicate) error {
	v.Type = "always"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsExactPredicate returns the union data inside the Predicate as a ExactPredicate
func (t Predicate) AsExactPredicate() (ExactPredicate, error) {
	var body ExactPredicate
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromExactPredicate overwrites any union data inside the Predicate as the provided ExactPredicate
func (t *Predicate) FromExactPredicate(v ExactPredicate) error {
	v.Type = "exact"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeExactPredicate performs a merge with any union data inside the Predicate, using the provided ExactPredicate
func (t *Predicate) MergeExactPredicate(v ExactPredicate) error {
	v.Type = "exact"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRegexPredicate returns the union data inside the Predicate as a RegexPredicate
func (t Predicate) AsRegexPredicate() (RegexPredicate, error) {
	var body RegexPredicate
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRegexPredicate overwrites any union data inside the Predicate as the provided RegexPredicate
func (t *Predicate) FromRegexPredicate(v RegexPredicate) error {
	v.Type = "regex"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRegexPredicate performs a merge with any union data inside the Predicate, using the provided RegexPredicate
func (t *Predicate) MergeRegexPredicate(v RegexPredicate) error {
	v.Type = "regex"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Predicate) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Predicate) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "always":
		return t.AsAlwaysPredicate()
	case "exact":
		return t.AsExactPredicate()
	case "regex":
		return t.AsRegexPredicate()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Predicate) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Predicate) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
