// Package apiv3 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.0 DO NOT EDIT.
package apiv3

import (
	"encoding/json"
	"errors"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for AlwaysPredicateType.
const (
	Always AlwaysPredicateType = "always"
)

// Defines values for EdgeOperation.
const (
	Append EdgeOperation = "append"
	Noop   EdgeOperation = "noop"
	Save   EdgeOperation = "save"
)

// Defines values for ExactPredicateType.
const (
	Exact ExactPredicateType = "exact"
)

// Defines values for RegexPredicateType.
const (
	Regex RegexPredicateType = "regex"
)

// AlwaysPredicate Переход по ребру осуществляется на любое сообщение пользователя.
type AlwaysPredicate struct {
	Type AlwaysPredicateType `json:"type"`
}

// AlwaysPredicateType defines model for AlwaysPredicate.Type.
type AlwaysPredicateType string

// Bot Сущность, связывающая между собой сценарий (Script) и запуски телеграм-бота (Run).
type Bot struct {
	// CreatedAt Метка времени создания бота.
	CreatedAt time.Time `json:"createdAt"`

	// Desc Человекочитаемое описание назначения бота.
	Desc string `json:"desc"`

	// Id Уникальный ID бота.
	Id string `json:"id"`

	// OwnerID ID владельца бота.
	OwnerID int64 `json:"ownerID"`

	// ScriptID ID сценария для бота.
	ScriptID string `json:"scriptID"`

	// UpdatedAt Метка времени последнего обновления бота.
	UpdatedAt time.Time `json:"updatedAt"`
}

// CreateBotRequest defines model for CreateBotRequest.
type CreateBotRequest struct {
	// Desc Человекочитаемое описание назначения бота.
	Desc string `json:"desc"`

	// ScriptID ID сценария для бота.
	ScriptID string `json:"scriptID"`

	// Token Telegram-токен бота, полученный через @BotFather.
	Token Token `json:"token"`
}

// CreateBotResponse defines model for CreateBotResponse.
type CreateBotResponse struct {
	// BotID Уникальный ID бота.
	BotID string `json:"botID"`
}

// CreateScriptRequest defines model for CreateScriptRequest.
type CreateScriptRequest struct {
	// Desc Человекочитаемое описание назначения сценария.
	Desc string `json:"desc"`

	// Entries Неупорядоченный непустой массив точек входа сценария.
	Entries []Entry `json:"entries"`

	// Nodes Неупорядоченный непустой массив узлов сценария.
	Nodes []Node `json:"nodes"`
}

// CreateScriptResponse defines model for CreateScriptResponse.
type CreateScriptResponse struct {
	// ScriptID Уникальный ID сценария.
	ScriptID string `json:"scriptID"`
}

// Edge Обозначают связь между узлами как переход в результате ответа пользователя.
type Edge struct {
	// Operation Действие, которое выполнится в результате перехода пользователя по ребру. - noop. Ничего не происходит. Подходит для использования в меню и промежуточных узлах. - save. Сохраняет ответ или перезаписывает предыдущий. Подходит в большинстве ситуаций. - append. Добавляет ответ к предыдущему. Подходит для вопросов с множественным выбором.
	Operation EdgeOperation `json:"operation"`

	// Predicate Predicate описывает условие перехода по ребру.
	Predicate Predicate `json:"predicate"`

	// To State узла, к которому совершается переход.
	To int `json:"to"`
}

// EdgeOperation Действие, которое выполнится в результате перехода пользователя по ребру. - noop. Ничего не происходит. Подходит для использования в меню и промежуточных узлах. - save. Сохраняет ответ или перезаписывает предыдущий. Подходит в большинстве ситуаций. - append. Добавляет ответ к предыдущему. Подходит для вопросов с множественным выбором.
type EdgeOperation string

// Entry Точка входа в сценарий бота. Пользователь может вызвать точку входу командой /<entry> (как, например, /start). Может быть вызвана рассылкой по такому же ключу.
type Entry struct {
	// Key Ключ точки входа.
	Key string `json:"key"`

	// Start Указатель на State узла, с которого начинается выполнение сценария.
	Start int `json:"start"`
}

// ExactPredicate Переход по ребру осуществляется при полном совпадении строки text с сообщением пользователя.
type ExactPredicate struct {
	Text string             `json:"text"`
	Type ExactPredicateType `json:"type"`
}

// ExactPredicateType defines model for ExactPredicate.Type.
type ExactPredicateType string

// GetBotResponse Сущность, связывающая между собой сценарий (Script) и запуски телеграм-бота (Run).
type GetBotResponse = Bot

// GetScriptResponse Сценарий бота. Является объединением узлов (Node), точек входа (Entry). Гарантируется связность всех узлов относительно любой точки входа Entry.
type GetScriptResponse = Script

// GetScriptsResponse defines model for GetScriptsResponse.
type GetScriptsResponse = []Script

// Message Любое сообщение в Telegram. На данный момент описывается текстом, но в будущем добавится поддержка файлов.
type Message struct {
	Text string `json:"text"`
}

// Node Минимальная структурная единица сценария Script. Представляет собой: - сообщения, которые отправляются пользователю (Message); - исходящие рёбра, обозначающие переход пользователя к следующему состоянию (узлу, Node); - опции для пользователя (кнопки).
type Node struct {
	// Edges Массив исходящих рёбер узла.
	Edges *[]Edge `json:"edges,omitempty"`

	// Messages Массив отправляемых ботом сообщений при вхождении в узел.
	Messages []Message `json:"messages"`

	// Options Массив кнопок (опций) ответа для пользователя.
	Options *[]string `json:"options,omitempty"`

	// State Уникальный номер узла в сценарии бота.
	State int `json:"state"`

	// Title Человеко-читаемое название узла. В таблице ответов будет отображаться как заголовок столбца.
	Title string `json:"title"`
}

// PlainError defines model for PlainError.
type PlainError struct {
	// Message Сообщение об ошибке.
	Message string `json:"message"`
}

// Predicate Predicate описывает условие перехода по ребру.
type Predicate struct {
	union json.RawMessage
}

// RegexPredicate Переход по ребру осуществляется при совпадении с регулярным выражением pattern.
type RegexPredicate struct {
	Pattern string             `json:"pattern"`
	Type    RegexPredicateType `json:"type"`
}

// RegexPredicateType defines model for RegexPredicate.Type.
type RegexPredicateType string

// Script Сценарий бота. Является объединением узлов (Node), точек входа (Entry). Гарантируется связность всех узлов относительно любой точки входа Entry.
type Script struct {
	// CreatedAt Метка времени создания сценария.
	CreatedAt time.Time `json:"createdAt"`

	// Desc Человекочитаемое описание назначения сценария.
	Desc string `json:"desc"`

	// Entries Неупорядоченный непустой массив точек входа сценария.
	Entries []Entry `json:"entries"`

	// Id Уникальный ID сценария.
	Id string `json:"id"`

	// Nodes Неупорядоченный непустой массив узлов сценария.
	Nodes []Node `json:"nodes"`

	// UpdatedAt Метка времени последнего обновления сценария.
	UpdatedAt time.Time `json:"updatedAt"`
}

// Token Telegram-токен бота, полученный через @BotFather.
type Token = string

// ValidationError defines model for ValidationError.
type ValidationError = []ValidationErrorDetail

// ValidationErrorDetail defines model for ValidationErrorDetail.
type ValidationErrorDetail struct {
	// Code Код ошибки валидации для данного поля.
	Code string `json:"code"`

	// Field Название поля, вызвавшего ошибку валидации.
	Field string `json:"field"`

	// Message Сообщение об ошибке валидации для данного поля.
	Message string `json:"message"`
}

// CreateBotJSONRequestBody defines body for CreateBot for application/json ContentType.
type CreateBotJSONRequestBody = CreateBotRequest

// CreateScriptJSONRequestBody defines body for CreateScript for application/json ContentType.
type CreateScriptJSONRequestBody = CreateScriptRequest

// AsAlwaysPredicate returns the union data inside the Predicate as a AlwaysPredicate
func (t Predicate) AsAlwaysPredicate() (AlwaysPredicate, error) {
	var body AlwaysPredicate
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAlwaysPredicate overwrites any union data inside the Predicate as the provided AlwaysPredicate
func (t *Predicate) FromAlwaysPredicate(v AlwaysPredicate) error {
	v.Type = "always"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAlwaysPredicate performs a merge with any union data inside the Predicate, using the provided AlwaysPredicate
func (t *Predicate) MergeAlwaysPredicate(v AlwaysPredicate) error {
	v.Type = "always"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsExactPredicate returns the union data inside the Predicate as a ExactPredicate
func (t Predicate) AsExactPredicate() (ExactPredicate, error) {
	var body ExactPredicate
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromExactPredicate overwrites any union data inside the Predicate as the provided ExactPredicate
func (t *Predicate) FromExactPredicate(v ExactPredicate) error {
	v.Type = "exact"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeExactPredicate performs a merge with any union data inside the Predicate, using the provided ExactPredicate
func (t *Predicate) MergeExactPredicate(v ExactPredicate) error {
	v.Type = "exact"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRegexPredicate returns the union data inside the Predicate as a RegexPredicate
func (t Predicate) AsRegexPredicate() (RegexPredicate, error) {
	var body RegexPredicate
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRegexPredicate overwrites any union data inside the Predicate as the provided RegexPredicate
func (t *Predicate) FromRegexPredicate(v RegexPredicate) error {
	v.Type = "regex"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRegexPredicate performs a merge with any union data inside the Predicate, using the provided RegexPredicate
func (t *Predicate) MergeRegexPredicate(v RegexPredicate) error {
	v.Type = "regex"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Predicate) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Predicate) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "always":
		return t.AsAlwaysPredicate()
	case "exact":
		return t.AsExactPredicate()
	case "regex":
		return t.AsRegexPredicate()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Predicate) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Predicate) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
